server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: abc123
    url: jdbc:mysql://127.0.0.1:3306/paper
    username: root
  jpa:
    show-sql: true
  thymeleaf:
    prefix: /pages/
    suffix: .jsp
# 开启MyBatis打印日志
#logging:
#    level:
#        com.lonton.project.dao:
##mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
